#!/usr/bin/env python3
"""Shared ANTIBIOTICS_50 constant used by all pipeline scripts."""

ANTIBIOTICS_50 = [
    "ampicillin",
    "amikacin",
    "amoxicillin",
    "amoxicillin-clavulanic acid",
    "azithromycin",
    "aztreonam",
    "cefazolin",
    "cefepime",
    "cefoxitin",
    "ceftazidime",
    "ceftriaxone",
    "cefuroxime",
    "chloramphenicol",
    "ciprofloxacin",
    "clarithromycin",
    "clindamycin",
    "colistin",
    "daptomycin",
    "doxycycline",
    "ertapenem",
    "erythromycin",
    "fosfomycin",
    "gentamicin",
    "imipenem",
    "kanamycin",
    "levofloxacin",
    "linezolid",
    "meropenem",
    "minocycline",
    "moxifloxacin",
    "nalidixic acid",
    "nitrofurantoin",
    "norfloxacin",
    "ofloxacin",
    "oxacillin",
    "penicillin",
    "piperacillin",
    "piperacillin-tazobactam",
    "polymyxin b",
    "rifampin",
    "spectinomycin",
    "streptomycin",
    "sulfamethoxazole",
    "teicoplanin",
    "tetracycline",
    "tigecycline",
    "tobramycin",
    "trimethoprim",
    "trimethoprim-sulfamethoxazole",
    "vancomycin",
]
